language: python
python:
  - "3.3"
  - "3.4"
install:
  - pip install --upgrade pip
  - pip install virtualenv
  - virtualenv jepvenv
  - source jepvenv/bin/activate
  - pip list
  - pip install -e .
  - pip list
script:
  - python setup.py test
