<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mcmake</string>
	</array>
	<key>name</key>
	<string>Mike CMake</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Built in command</string>
			<key>match</key>
			<string>(?i)endfunction|endmacro|macro|endif|elseif|else|if|return|set|endforeach|foreach|list</string>
			<key>name</key>
			<string>keyword.control.mcmake</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>COMMAND operators</string>
			<key>match</key>
			<string>(?i)not|and|strequal|equal|append</string>
			<key>name</key>
			<string>keyword.operator.mcmake</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.mcmake</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.mcmake</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\$({[^}]*})</string>
					<key>name</key>
					<string>variable.parameter.mcmake</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Number</string>
			<key>match</key>
			<string>-?\d+</string>
			<key>name</key>
			<string>constant.numeric.mcmake</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.percentage.mcmake</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.mcmake</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.mcmake</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function definition</string>
			<key>match</key>
			<string>(function)\s*(\()\s*(\w+)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\$)({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.mcmake</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>variable.parameter.mcmake</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>constant.character.mcmake</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mcmake</string>
	<key>uuid</key>
	<string>1f9e3579-4e31-463d-8a32-aa14a9e8cce7</string>
</dict>
</plist>
